require 'rubygems'
require 'rake'
require 'rake/extensiontask'

#require File.join(File.expand_path(File.dirname(__FILE__)), "lib")

MAKE = 'make'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "tidy-ext"
    gem.summary = "HTML Tidy library implemented as a Ruby extension."
    gem.description = <<-EOS
    Tidies up web pages.
    EOS
    gem.email = "carl.douglas@gmail.com"
    gem.homepage = "http://github.com/carld/tidy"
    gem.authors = ["Carl Douglas"]
    gem.extensions = FileList["ext/**/extconf.rb"]
  end
  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: gem install jeweler"
end

desc "Launch an IRB session with the environment loaded"
task :console do
  exec("irb -I lib -r tidy/alone")
end

require 'spec/rake/spectask'
Spec::Rake::SpecTask.new(:spec) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.spec_files = FileList['spec/**/*_spec.rb']
end

Spec::Rake::SpecTask.new(:rcov) do |spec|
  spec.libs << 'lib' << 'spec'
  spec.pattern = 'spec/**/*_spec.rb'
  spec.rcov = true
end

task :spec => :check_dependencies

task :default => :spec

require 'rake/rdoctask'
Rake::RDocTask.new do |rdoc|
  version = File.exist?('VERSION') ? File.read('VERSION') : ""

  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = "tidy #{version}"
  rdoc.rdoc_files.include('README*')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

Rake::ExtensionTask.new('tidy')


